name: Generate Horse Racing Ticket

on:
  push:
    branches:
      - main

jobs:
  generate-ticket:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードを取得
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 日本語フォントのインストール
      - name: Install Japanese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      # Node.js環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 必要な依存関係をインストール
      - name: Install Puppeteer
        run: |
          npm install puppeteer

      # HTMLファイルを生成
      - name: Create HTML File
        run: |
          cat <<EOF > ticket.html
          <!DOCTYPE html>
          <html lang="ja">
          <head>
            <meta charset="UTF-8">
            <title>馬券風デザイン</title>
            <style>
              body {
                font-family: "Noto Sans JP", Arial, sans-serif;
                background-color: #f4f4f4;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
              }
              .ticket {
                width: 400px;
                border: 2px solid black;
                background: #ffffff;
                padding: 10px;
                box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.2);
                position: relative;
              }
              .header {
                display: flex;
                justify-content: space-between;
                font-size: 12px;
                margin-bottom: 5px;
              }
              .race-number {
                font-size: 24px;
                font-weight: bold;
                text-align: center;
                margin-bottom: 10px;
              }
              .bet-info {
                display: flex;
                justify-content: space-between;
                font-size: 14px;
                margin-bottom: 10px;
              }
              .bet-type {
                text-align: center;
                font-size: 16px;
                font-weight: bold;
                margin-bottom: 10px;
              }
              .table {
                width: 100%;
                border: 1px solid black;
                border-collapse: collapse;
                margin-bottom: 10px;
              }
              .table th, .table td {
                border: 1px solid black;
                padding: 5px;
                text-align: center;
              }
              .footer {
                font-size: 12px;
                display: flex;
                justify-content: space-between;
              }
              .footer .total {
                font-size: 14px;
                font-weight: bold;
              }
              .watermark {
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                font-size: 50px;
                color: rgba(0, 255, 0, 0.2);
                white-space: nowrap;
                pointer-events: none;
                z-index: -1;
              }
            </style>
          </head>
          <body>
            <div class="ticket">
              <div class="header">
                <span>2017年4回3日</span>
                <span>東京 10レース</span>
              </div>
              <div class="race-number">3連単</div>
              <div class="bet-info">
                <span>TRIFECTA</span>
                <span>軸2頭流し</span>
              </div>
              <div class="bet-type">WHEEL</div>
              <table class="table">
                <tr>
                  <th>1頭目</th>
                  <td>2</td>
                </tr>
                <tr>
                  <th>2頭目</th>
                  <td>10</td>
                </tr>
                <tr>
                  <th>3頭目</th>
                  <td>13, 4, 7, 8</td>
                </tr>
              </table>
              <div class="footer">
                <span>組み合わせ数: 5×6</span>
                <span class="total">合計: 300,000円</span>
              </div>
              <div class="watermark">JRA</div>
            </div>
          </body>
          </html>
          EOF

      # HTMLから画像を生成
      - name: Generate Ticket Image
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox', '--fontconfig'] });
            const page = await browser.newPage();
            await page.setContent(require('fs').readFileSync('ticket.html', 'utf8'));
            await page.screenshot({ path: 'ticket.png' });
            await browser.close();
          })();
          "

      # 生成された画像をコミット
      - name: Commit Ticket Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ticket.png
          git commit -m "Generate horse racing ticket"
          git push || echo "No changes to push"
