name: Generate Horse Racing Ticket

on:
  push:
    branches:
      - main

jobs:
  generate-ticket:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードを取得
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 日本語フォントのインストール
      - name: Install Japanese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      # Node.js環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 必要な依存関係をインストール
      - name: Install Puppeteer
        run: |
          npm install puppeteer

      # HTMLファイルを生成
      - name: Create HTML File
        run: |
          cat <<EOF > ticket.html
          <!DOCTYPE html>
          <html lang="ja">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
              body {
                font-family: 'Noto Sans JP', sans-serif;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                background-color: #f0f0f0;
              }
              .ticket {
                width: 800px;
                height: 400px;
                background: white;
                border: 2px solid black;
                position: relative;
                padding: 20px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
              }
              .ticket-header {
                display: flex;
                justify-content: space-between;
                align-items: center;
              }
              .race-info {
                font-size: 20px;
                font-weight: bold;
              }
              .win {
                position: absolute;
                top: 50px;
                right: 20px;
                font-size: 40px;
                font-weight: bold;
                color: #007700;
              }
              .details {
                margin-top: 20px;
                font-size: 18px;
              }
              .details .horse {
                font-size: 24px;
                font-weight: bold;
              }
              .qr {
                position: absolute;
                bottom: 20px;
                left: 20px;
              }
            </style>
          </head>
          <body>
            <div class="ticket">
              <div class="ticket-header">
                <div class="race-info">2017年5回7日 中山 10レース</div>
                <div>第140回 中山大障害 (J・GI)</div>
              </div>
              <div class="details">
                <div>単勝</div>
                <div class="horse">7 オジュウチョウサン</div>
                <div>100円</div>
              </div>
              <div class="win">WIN</div>
              <div class="qr">
                <img src="https://via.placeholder.com/100" alt="QR Code">
              </div>
            </div>
          </body>
          </html>
          EOF

      # HTMLから画像を生成
      - name: Generate Ticket Image
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox', '--fontconfig'] });
            const page = await browser.newPage();
            await page.setContent(require('fs').readFileSync('ticket.html', 'utf8'));
            await page.screenshot({ path: 'ticket.png' });
            await browser.close();
          })();
          "

      # 生成された画像をコミット
      - name: Commit Ticket Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ticket.png
          git commit -m "Generate horse racing ticket"
          git push || echo "No changes to push"
