name: Generate Horse Racing Ticket

on:
  push:
    branches:
      - main

jobs:
  generate-ticket:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードを取得
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Node.js環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 必要な依存関係をインストール
      - name: Install Puppeteer
        run: |
          npm install puppeteer

      # HTMLから画像を生成
      - name: Generate Ticket Image
        run: |
          echo '<!DOCTYPE html>
          <html lang="ja">
          <head>
            <meta charset="UTF-8">
            <title>馬券風デザイン</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 20px;
                background-color: #f4f4f4;
              }
              .ticket {
                border: 2px solid black;
                width: 360px;
                padding: 10px;
                background: #ffffff;
                box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.1);
                margin: auto;
              }
              .header {
                display: flex;
                justify-content: space-between;
                font-size: 14px;
                margin-bottom: 10px;
              }
              .race-info {
                text-align: center;
                font-size: 20px;
                font-weight: bold;
                margin-bottom: 10px;
              }
              .section {
                margin-bottom: 10px;
              }
              .section-title {
                font-weight: bold;
                margin-bottom: 5px;
              }
              .bets {
                text-align: center;
                font-size: 18px;
                font-weight: bold;
                margin-bottom: 10px;
              }
              .table {
                width: 100%;
                border-collapse: collapse;
                text-align: center;
                margin-bottom: 10px;
              }
              .table th, .table td {
                border: 1px solid black;
                padding: 5px;
              }
              .footer {
                text-align: right;
                font-size: 14px;
                margin-top: 10px;
              }
            </style>
          </head>
          <body>
            <div class="ticket">
              <div class="header">
                <div>2024年4回3日</div>
                <div>東京 10レース</div>
              </div>
              <div class="race-info">ダービーチャレンジ</div>
              <div class="section">
                <div class="section-title">TRIFECTA - フォーメーション</div>
                <div class="bets">3連単</div>
              </div>
              <table class="table">
                <tr>
                  <th>1頭目</th>
                  <td>2</td>
                </tr>
                <tr>
                  <th>2頭目</th>
                  <td>10</td>
                </tr>
                <tr>
                  <th>3頭目</th>
                  <td>4, 7, 8</td>
                </tr>
              </table>
              <div class="footer">
                組み合わせ数: 5点<br>
                購入金額: 100円 × 5点 = 500円
              </div>
            </div>
          </body>
          </html>' > ticket.html

          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
            const page = await browser.newPage();
            await page.setContent(require('fs').readFileSync('ticket.html', 'utf8'));
            await page.screenshot({ path: 'ticket.png' });
            await browser.close();
          })();
          "

      # 生成された画像をコミット
      - name: Commit Ticket Image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ticket.png
          git commit -m "Generate horse racing ticket"
          git push
